---
- name: Create resource group
  ansible.builtin.include_role:
    name: resource_group
  when: rg_info.resourcegroups | length == 0

- name: Ensure public ip exists
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_load_balancer.public_ip_name | default(azure_load_balancer.name + '-public-ip') }}"
    domain_name: "{{ azure_load_balancer.domain_name | default(omit) }}"
    sku: "{{ azure_load_balancer.sku | default(omit) }}"
    allocation_method: "{{ (azure_load_balancer.sku is defined and azure_load_balancer.sku == 'Standard') | ternary('Static', omit) }}"

- name: Create/Update load balancer
  azure.azcollection.azure_rm_loadbalancer:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_load_balancer.name }}"
    frontend_ip_configurations: "{{ azure_load_balancer.frontend_ip_configurations | default([{'name': 'default', 'public_ip_address': azure_load_balancer.public_ip_name\
      \ | default(azure_load_balancer.name + '-public-ip')}]) }}"
    backend_address_pools: "{{ azure_load_balancer.backend_address_pools | default([{'name': 'default'}]) }}"
    probes: "{{ azure_load_balancer.probes | default(omit) }}"
    load_balancing_rules: "{{ azure_load_balancer.rules | default(omit) }}"
    sku: "{{ azure_load_balancer.sku | default(omit) }}"
    tags: "{{ azure_load_balancer.tags | default(omit) }}"
