---
azure_vm_name: "webapp-vm-"
azure_vm_user: "ansible"
azure_vm_user_password: "4fB5In3ueO7,"
azure_vm_image:
  offer: RHEL
  publisher: RedHat
  sku: '7-LVM'
  version: latest
azure_vm_size: "Standard_A2"
azure_number_vm: 3

# Source
azure_resource_group: source_rg
source_resource_group: "{{ azure_resource_group }}"
source_region: eastus

# Destination
destination_resource_group: dest_rg
destination_region: canadacentral

# PostgreSQL Server variables
azure_postgresql_name: "{{ azure_resource_group | replace('_', '-') }}-dbserver"
azure_postgresql_admin_username: "ansible"
azure_postgresql_admin_password: "4fB5In3ueO7,"
azure_postgresql_database_instances:
  - name: pyapp
    charset: UTF8
azure_postgresql_firewall_rules:
  - name: allow_all
    start_ip_address: 0.0.0.0
    end_ip_address: 255.255.255.255

# Application variables
py_application:
  env: "development"
  admin_user: "admin"
  admin_password: "admin"
  docker_image: "pywebapp"
  docker_dir: "/app/pyapp"
  data_dir: "/tmp/myapp_data"
  container_name: "myapp-container"

application_force_init: false

application_src: "https://github.com/abikouo/webapp_pyflask_demo.git"

playbook_number_forks: 15