---
- name: Get security group resource
  azure_rm_securitygroup_info:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_security_group.name }}"
  register: sg_info

- name: Init empty list of rules
  set_fact:
    new_sg_rules: []

- name: Persist rules that will not be removed
  set_fact:
    new_sg_rules: "{{ new_sg_rules + [{ 'name': rule.name, 'protocol': rule.properties.protocol, 'access': rule.properties.access,
                    'destination_address_prefix': rule.properties.destinationAddressPrefix, 'destination_port_range': rule.properties.destinationPortRanges,
                    'direction': rule.properties.direction, 'priority': rule.properties.priority, 'source_address_prefix': rule.properties.sourceAddressPrefix,
                    'source_port_range': rule.properties.sourcePortRange, }] }}"
  with_items: "{{ sg_info.securitygroups[0].properties.securityRules }}"
  loop_control:
    loop_var: rule
  when: rule.name not in azure_security_group.rules_to_remove

- name: Update security group with specified rules removed
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_security_group.name }}"
    purge_rules: yes
    rules: "{{ new_sg_rules }}"
    tags: "{{ azure_tags | default(omit) }}"