---
azure_manage_postgresql_operation: create
azure_manage_postgresql_postgresql_version: "9.5"
azure_manage_postgresql_postgresql_settings: []
azure_manage_postgresql_postgresql_firewall_rules: []
azure_manage_postgresql_postgresql_database_instances: []
azure_manage_postgresql_delete_server: false
azure_manage_postgresql_delete_resource_group: false
