---
- name: Check Region Setting
  fail:
    msg: "Azure Region must be defined as azure_region"
  when: azure_region is not defined

- name: create resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
    tags: "{{ azure_resource_group_tags | default(omit) }}"
  register: result

- name: lock resource group
  azure_rm_lock:
    name: "{{ azure_resource_group }}-lock"
    level: "can_not_delete"
    managed_resource_id: "{{ result.state.id }}"
  when: azure_lock_resource_group | bool